// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Email        string      `json:"email"`
	UserID       pgtype.Int8 `json:"user_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}
