// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	GetByEmail(ctx context.Context, email string) (User, error)
	GetById(ctx context.Context, userID pgtype.Int8) (User, error)
	Remove(ctx context.Context, userID pgtype.Int8) error
}

var _ Querier = (*Queries)(nil)
