{
 "title": "Webbeded-platform",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "users-management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"app - users-management\",code=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_requests_total{job=\"app - users-management\",code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg time duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed request per min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{code!=\"200\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}