// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64       `json:"id"`
	Email     string      `json:"email"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Group     pgtype.Text `json:"group"`
}
