// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package users

import (
	"context"
)

const getById = `-- name: GetById :one
SELECT id, email, first_name, last_name, "group"
FROM "Users" u
WHERE u.id = $1
`

func (q *Queries) GetById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Group,
	)
	return i, err
}
